/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 .\public\models\nissan-car.glb 
Author: Lexyc16 (https://sketchfab.com/Lexyc16)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/nissan-fairlady-z-s30240z-1978-0d9286ebb8cc426e993e1d398b874a34
Title: Nissan Fairlady Z S30(240Z) 1978
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/nissan-car.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Material.019']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Material.034']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['Material.030']} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['Material.026']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['Material.028']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['Material.039']} />
        <mesh geometry={nodes.Object_13.geometry} material={materials['Material.046']} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['Material.048']} />
        <mesh geometry={nodes.Object_15.geometry} material={materials['plate_d-dds']} />
        <mesh geometry={nodes.Object_16.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_17.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_19.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Object_20.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Object_21.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Object_22.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Object_23.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Object_24.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Object_25.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Object_26.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Object_27.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Object_28.geometry} material={materials['Material.016']} />
        <mesh geometry={nodes.Object_29.geometry} material={materials['Material.018']} />
        <mesh geometry={nodes.Object_30.geometry} material={materials['Material.023']} />
        <mesh geometry={nodes.Object_31.geometry} material={materials['Material.023']} />
        <mesh geometry={nodes.Object_32.geometry} material={materials['Material.023']} />
        <mesh geometry={nodes.Object_33.geometry} material={materials['Material.023']} />
        <mesh geometry={nodes.Object_34.geometry} material={materials['Material.021']} />
        <mesh geometry={nodes.Object_35.geometry} material={materials['Material.021']} />
        <mesh geometry={nodes.Object_36.geometry} material={materials['Material.025']} />
        <mesh geometry={nodes.Object_37.geometry} material={materials['Material.035']} />
        <mesh geometry={nodes.Object_38.geometry} material={materials['Material.035']} />
        <mesh geometry={nodes.Object_39.geometry} material={materials['Material.029']} />
        <mesh geometry={nodes.Object_40.geometry} material={materials['Material.024']} />
        <mesh geometry={nodes.Object_41.geometry} material={materials['Material.037']} />
        <mesh geometry={nodes.Object_42.geometry} material={materials['Material.043']} />
        <mesh geometry={nodes.Object_43.geometry} material={materials['Material.043']} />
        <mesh geometry={nodes.Object_44.geometry} material={materials['Material.042']} />
        <mesh geometry={nodes.Object_45.geometry} material={materials['Material.044']} />
      </group>
    </group>
  )
}

useGLTF.preload('/nissan-car.glb')
