/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 .\public\models\screen.glb 
*/

import { PositionalAudio, useGLTF, useVideoTexture } from '@react-three/drei';
import { useState } from 'react';

function VideoMaterial({ url, isPlaying }: any) {
  const texture = useVideoTexture(url, { start: isPlaying });
  return <meshBasicMaterial map={texture} toneMapped={false} />;
}

export const Screen = ({ position, rotation, visible, scale }: any) => {
  const [isPlaying, setIsPlaying] = useState(false);
  const { nodes, materials }: any = useGLTF('/models/screen.glb');

  const handlePlay = () => {
    setIsPlaying(true);
  };

  return (
    <>
      <group>
        <group
          scale={scale}
          dispose={null}
          position={position}
          rotation={rotation}
          visible={visible}
          onClick={handlePlay}
        >
          <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material}>
            <VideoMaterial
              url="/textures/nissan-tex.mp4"
              isPlaying={isPlaying}
            />
          </mesh>
        </group>
        <group
          scale={[3, 3, 1.4]}
          dispose={null}
          position={[0, 0.56, 15.04]}
          rotation={rotation}
          visible={visible}
        >
          <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material}>
            <meshBasicMaterial color={'#000'} />
          </mesh>
          <PositionalAudio
            autoplay
            loop={false}
            url="/audio/nissan-audio.mp3"
            distance={3}
          />
        </group>
      </group>
    </>
  );
};

useGLTF.preload('/models/screen.glb');
